config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    '/auth/:provider'          => 'omniauth#auth',    as: :auth
  get    '/auth/:provider/callback' => 'session#create'
  get    '/auth/failure'            => 'session#failure'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

  root "restaurants#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :restaurant
  attachment :image
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CUISINES = [ "Cuisine", "American", "Mexican", "Italian", "French", "Greek", "Chinese", "Japanese", "Vietnamese", "Korean" ]
  PRICES = [
    ["Price", 0],
    ["$", 1],
    ["$$", 2],
    ["$$$", 3],
    ["$$$$", 4],
    ["$$$$$", 5]
  ]
  attachment :menu

  has_many :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Factory method to create a user from some omniauth data
  # Omniauth will use this to build a *NEW* user for us
  def self.from_omniauth(authentication_data)
    user = User.where(provider: authentication_data['provider'],
                      uid: authentication_data['uid']).first_or_create

    Rails.logger.debug "The user is #{user.inspect}"

    user.name         = authentication_data.info.name
    user.nickname     = authentication_data.info.nickname
    user.access_token = authentication_data.info.access_token

    user.save!

    Rails.logger.debug "After saving, the user is #{user.inspect}"

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Assign the current user
  def current_user=(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  # Returns a boolean representing if the user is logged in
  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  # Method to use in filter to ensure the user is logged in
  def authenticate!
    unless logged_in?
      redirect_to auth_path(provider: 'github')
    end
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate!, except: [:index, :show]

  # GET /restaurants
  def index
    if params[:cuisine]
      @restaurants = Restaurant.where(cuisine: params[:cuisine])
    elsif params[:price]
      @restaurants = Restaurant.where(price: params[:price])
    else
      @restaurants = Restaurant.all
    end
  end

  # GET /restaurants/1
  def show
    @restaurant = Restaurant.find(params[:id])
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone, :website, :hours, :price, :cuisine, :menu)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  # logging in
  def new
  end

  # handle the post from the login page
  def create
    self.current_user = User.from_omniauth(request.env['omniauth.auth'])

    if current_user
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  # logout
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  # Show the failure page
  def failure
    # TODO, create failure.html.erb
  end
end

app/controllers/sessions_controller.rb
class SessionController < ApplicationController
  # logging in
  def new
  end

  # handle the post from the login page
  def create
    self.current_user = User.from_omniauth(request.env['omniauth.auth'])

    if current_user
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  # logout
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  # Show the failure page
  def failure
    # TODO, create failure.html.erb
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def price_as_dollarsigns(price)
    if price.nil? || price <= 0
      "N/A"
    else
      "$" * [price, 5].min
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title
      = RestaurantApp

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header.logo
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to root_path, class: "navbar-brand" do
            𝓔𝓪𝓽 𝓢𝓽. 𝓟𝓮𝓽𝓮
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            - if logged_in?
              %li
                = link_to current_user.name, '#'
              %li
                = link_to 'Not you? Logout', logout_path
              %li
                = link_to new_restaurant_path do
                  Add Restaurant
            - else
              %li
                = link_to 'Login with Github', auth_path(provider: 'github')

    .container.background
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/restaurants/_form.html.haml
= form_for @restaurant, html: { class: "form-horizontal", role: "form" } do |f|
  -if @restaurant.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@restaurant.errors.count, "error")} prohibited this restaurant from being saved:"

      %ul
        - @restaurant.errors.full_messages.each do |msg|
          %li= msg

  .col-sm-10
    %p
      = f.text_field :name, class: 'form-control', placeholder: 'Name'
  .col-sm-10
    %p
      = f.text_field :address, class: 'form-control', placeholder: 'Address'
  .col-sm-10
    %p
      = f.text_field :phone, class: 'form-control', placeholder: 'Phone'
  .col-sm-10
    %p
      = f.text_field :website, class: 'form-control', placeholder: 'Website'
  .col-sm-10
    %p
      = f.text_area :hours, class: 'form-control', placeholder: 'Hours'
  .col-sm-10
    %p
      = f.select :price, options_for_select( Restaurant::PRICES, @restaurant.cuisine), class: 'form-control'
  .col-sm-10
    %p
      = f.select :cuisine, options_for_select( Restaurant::CUISINES, @restaurant.cuisine), class: 'form-control'
  .col-sm-4
    %p
      = f.attachment_field :menu, class: 'form-control'
    %p
      .form-group
      = f.submit class: 'btn btn-success'

app/views/restaurants/edit.html.haml
%img#bg{:alt => "https://upload.wikimedia.org/wikipedia/commons/6/66/Saint_Petersburg_Florida_at_Night_from_McNulty_Lofts.png", :src => "https://upload.wikimedia.org/wikipedia/commons/6/66/Saint_Petersburg_Florida_at_Night_from_McNulty_Lofts.png"}/

%h1.new-header
  𝓔𝓭𝓲𝓽 𝓡𝓮𝓼𝓽𝓪𝓾𝓻𝓪𝓷𝓽

.col-md-6.restaurant-listing-edit
  = image_tag attachment_url(@restaurant.photos.first, :image), class: 'img-responsive'

.col-md-6
  .row
    = render 'form'
  .col-sm-2.form-button
    = link_to @restaurant, class: 'btn btn-primary' do
      %span.glyphicon.glyphicon-info-sign
      Back
  .col-sm-2.form-button
    = link_to @restaurant, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }, method: :delete do
      %span.glyphicon.glyphicon-remove
      Delete

app/views/restaurants/index.html.haml
%img#bg{:alt => "https://upload.wikimedia.org/wikipedia/commons/6/66/Saint_Petersburg_Florida_at_Night_from_McNulty_Lofts.png", :src => "https://upload.wikimedia.org/wikipedia/commons/6/66/Saint_Petersburg_Florida_at_Night_from_McNulty_Lofts.png"}/

.row
  .col-md-1
  .col-md-10
    %h1.index-header
      𝓡𝓮𝓼𝓽𝓪𝓾𝓻𝓪𝓷𝓽𝓼
  .col-md-1

.row
  .col-md-4.col-sm-4
    %p.filters-text
      𝓢𝓮𝓪𝓻𝓬𝓱 𝓫𝔂:
  .col-md-4.col-sm-4.col-xs-6.filters
    = form_tag(restaurants_path, method: "GET") do
      .form-group.span
        = select_tag :cuisine, options_for_select( Restaurant::CUISINES), class: 'form-control'
      = button_tag "Search", class: "btn btn-default"
  .col-md-4.col-sm-4.col-xs-6.filters
    = form_tag(restaurants_path, method: "GET") do
      .form-group
        = select_tag :price, options_for_select( Restaurant::PRICES), class: 'form-control'
      = button_tag "Search", class: "btn btn-default"

.row
  - @restaurants.each do |restaurant|
    .col-md-4
      = link_to restaurant do
        - restaurant.photos.each do |photo|
          .restaurant-index
            = image_tag attachment_url(photo, :image), class: 'img-responsive'
            .restaurant-details
              %h5
                %font{:size => "6"}= restaurant.name
              %p
                = price_as_dollarsigns(restaurant.price)
                •
                = restaurant.phone
              %p
                = restaurant.name
                •
                = restaurant.address

app/views/restaurants/new.html.haml
%img#bg{:alt => "https://upload.wikimedia.org/wikipedia/commons/6/66/Saint_Petersburg_Florida_at_Night_from_McNulty_Lofts.png", :src => "https://upload.wikimedia.org/wikipedia/commons/6/66/Saint_Petersburg_Florida_at_Night_from_McNulty_Lofts.png"}/

%h1.new-header
  𝓝𝓮𝔀 𝓡𝓮𝓼𝓽𝓪𝓾𝓻𝓪𝓷𝓽

.col-md-8.form
  = render 'form'

app/views/restaurants/show.html.haml
-# .page-header
-#   = link_to edit_restaurant_path(@restaurant), class: 'btn btn-primary' do
-#     %span.glyphicon.glyphicon-pencil
-#     Edit
-#   %h1
-#     = @restaurant.name

%img#bg{:alt => "https://upload.wikimedia.org/wikipedia/commons/6/66/Saint_Petersburg_Florida_at_Night_from_McNulty_Lofts.png", :src => "https://upload.wikimedia.org/wikipedia/commons/6/66/Saint_Petersburg_Florida_at_Night_from_McNulty_Lofts.png"}/

.col-md-6.restaurant-listing
  = image_tag attachment_url(@restaurant.photos.first, :image), class: 'img-responsive'

.col-md-6.restaurant-listing
  %h1
    = @restaurant.name
  %p
    Phone:
    = @restaurant.phone
  %p
    Price:
    = price_as_dollarsigns(@restaurant.price)
  %p
    Website:
    = @restaurant.website
  %p
    Hours:
    = @restaurant.hours
  %p
    Cuisine:
    = @restaurant.cuisine
  %p
    = link_to edit_restaurant_path(@restaurant), class: 'btn btn-default btn-edit' do
      %span.glyphicon.glyphicon-pencil
      Edit